# https://docs.github.com/code-security/reference/supply-chain-security/dependabot-options-reference
version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    open-pull-requests-limit: 99
    schedule:
      interval: "monthly"
      time: "19:00"
      timezone: "Asia/Tokyo"
    cooldown:
      default-days: 7
