name: FOSSA Scan

on:
  push:

jobs:
  fossa-scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: fossas/fossa-action@v1.4.0
        with:
          api-key: ${{ secrets.fossaApiKey }}
          run-tests: true
